apiVersion: apps/v1
kind: Deployment
metadata:
  name: choam-terminal-deployment
  namespace: choam-terminal
  labels:
    app: choam-terminal-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: choam-terminal-bot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: choam-terminal-bot
    spec:
      containers:
        - name: choam-terminal-bot
          image: ghcr.io/JDNorman/CHOAM-TERMINAL-bot:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 500Mi
              cpu: 100m
          env:
            - name: NODE_ENV
              value: 'production'
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: BOT_TOKEN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: BOT_TOKEN
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: NEW_RELIC_APP_NAME
            - name: NEW_RELIC_LISENCE_KEY
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: NEW_RELIC_LISENCE_KEY
      imagePullSecrets:
        -name: regcred