name: Build Image & Deploy
on:
  push:
    branches:
      - main
    # Ignore changes in docs folder
    paths-ignore:
      - 'docs/**'

env:
  version: 1.0.0

concurrency: cd

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    if: "!contains(github.event.head_commit.message, '#skip-ci')"

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Dry incremement patch version
        id: tag-dry-run
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: none
          WITH_V: true
          DRY_RUN: true

      - name: Set version for later
        run: |
          echo "Increnting version with '${{ steps.tag-dry-run.outputs.part }}' to '${{ steps.tag-dry-run.outputs.new_tag }}' from '${{ steps.tag-dry-run.outputs.tag }}'"
          tag=${{ steps.tag-dry-run.outputs.new_tag }}
          version=$(echo "$tag" | cut -b 2-)
          echo "version=$version" >> $GITHUB_ENV
      
      - name: Set npm version
        uses: reedyuk/npm-version@1.1.1
        with:
          version: 1.1.1
          package: ./
          git-tag-version: false
        env:
          version: ${{ env.version }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/JDNorman/choam-terminal-bot
          tags: |
            type=semver,pattern={{major}},value=${{ env.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.version }}

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Tag Docker image
        run: |
          docker tag ghcr.io/JDNorman/choam-terminal-bot:latest ghcr.io/JDNorman/choam-terminal-bot:${{ env.version }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/JDNorman/choam-terminal-bot:${{ env.version }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=local,src/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          load: false
          no-cache: false
          pull: false
          github-token: ***
        env:
          version: 0.0.0
      
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Increment patch version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none

  deploy:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: "!contains(github.event.head_commit.message, '#skip-ci')"
    needs: ['build'] # always run after build step

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG }}
          command: rollout restart deployment/choam-terminal-deployment -n=choam-terminal
          version: v1.21.0